spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.evnxztxzwamhrglfdzpb
spring.datasource.password=Ksy7da1Cp3SfvatP

jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9yTWFya2V0cGxhY2UyMDI2VGhhdElzTG9uZ0Vub3VnaA==
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# Supabase Storage (for product image uploads)
supabase.url=https://evnxztxzwamhrglfdzpb.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2bnh6dHh6d2FtaHJnbGZkenBiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NTIzMzkzMiwiZXhwIjoyMTAwODA5OTMyfQ.RETOBjbGx-81W_dUZq_tkmrxtqYJw4LUxgeVanS8qRk
supabase.bucket=product-images